import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import 'reactflow/dist/style.css';
import 'react-quill/dist/quill.snow.css';
import ToasterContext from './context/ToasterContext'
import getCurrentUser from './actions/getCurrentUser'
import AuthContext from './context/AuthContext'
import LayoutHome from './components/LayoutHome'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Projects Management',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  
  return (
    <html lang="en" suppressHydrationWarning={true} suppressContentEditableWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthContext>
          <ToasterContext />
          {currentUser === null ? (
            <>
              {children}
            </>
          ):(
            <LayoutHome>
              {children}
            </LayoutHome>
          )}
        </AuthContext>
      </body>
    </html>
  )
}
